version: '2'
services:
  dse-ops:
    image: dkanejs/dse-ops
    ports:
      - '8888:8888'
      - '8983:8983'
  dse-node-1:
    image: dkanejs/dse
    command: -s
    volumes:
      - dse-node-1-data:/data
      - dse-node-1-data:/logs
    ports:
      - '9042:9042'
    environment:
      - CLUSTER_NAME=Docker
      - STOMP_INTERFACE=dse-ops
      - SEEDS=dse-node-1,dse-node-2
    links:
      - dse-ops
      - dse-node-2
    depends_on:
      - dse-ops
  dse-node-2:
    image: dkanejs/dse
    command: -s
    volumes:
      - dse-node-2-data:/data
      - dse-node-2-data:/logs
    environment:
      - CLUSTER_NAME=Docker
      - STOMP_INTERFACE=dse-ops
      - SEEDS=dse-node-1,dse-node-2
    links:
      - dse-ops
    depends_on:
      - dse-ops
volumes:
  dse-node-1-data:
    driver: local
  dse-node-2-data:
    driver: local